[project]
name = "dsa103-githubtest-session05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rea6", email = "93106924+Rea6@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
dsa103-githubtest-session05 = "dsa103_githubtest_session05:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
